//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemOfChair.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.InstituteGroups = new HashSet<InstituteGroup>();
        }
    
        public int InstituteID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InstituteGroup> InstituteGroups { get; set; }
    }
}
