//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemOfChair.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shedule
    {
        public int SheduleID { get; set; }
        //public Nullable<int> InstituteGroup { get; set; }
        public int InstituteGroup { get; set; }
        public int ClassNumber { get; set; }
        public int DayOfWeek { get; set; }
        public string ClassName { get; set; }
        public string ClassRoom { get; set; }
        public Nullable<int> ProfessorID { get; set; }
        public bool IsNumerator { get; set; }
    
        public virtual InstituteGroup InstituteGroup1 { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
