//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemOfChair.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstituteGroup
    {
        public InstituteGroup()
        {
            this.Shedules = new HashSet<Shedule>();
        }
    
        public int InstituteGroupID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InstituteID { get; set; }
    
        public virtual Institute Institute { get; set; }
        public virtual ICollection<Shedule> Shedules { get; set; }
    }
}
