//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemOfChair.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_information_system_of_chair : DbContext
    {
        public db_information_system_of_chair()
            : base("name=db_information_system_of_chair")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Institute> Institutes { get; set; }
        public DbSet<InstituteGroup> InstituteGroups { get; set; }
        public DbSet<Professor> Professors { get; set; }
        public DbSet<Shedule> Shedules { get; set; }
    }
}
