//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystemOfChair
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.Shedules = new HashSet<Shedule>();
        }
    
        public int ProfessorID { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Shedule> Shedules { get; set; }
    }
}
